package main

import (
	"context"
	"fmt"
	"strings"

	"github.com/dagger/dagger/.dagger/internal/dagger"
)

// Develop the Dagger Go SDK
func (sdk *SDK) Go(
	// +defaultPath="/"
	// +ignore=[
	//  "*",
	// 	"!sdk/go",
	//  "!**/go.mod",
	//  "!**/go.sum",
	//  "!cmd/codegen",
	//  "!engine/slog",
	// ]
	source *dagger.Directory,
	// FIXME: add a source argument when spun out
) GoSDK {
	return GoSDK{
		Source: source,
	}
}

type GoSDK struct {
	Source *dagger.Directory
}

func (t GoSDK) Name() string {
	return "go"
}

// Test the Go SDK
// FIXME: merge into common go toolchain
func (t GoSDK) Test(ctx context.Context) (CheckStatus, error) {
	_, err := t.DevContainer().
		WithExec([]string{"go", "test", "-v", "-skip=TestProvision", "./..."}).
		Sync(ctx)
	return CheckCompleted, err
}

func (t GoSDK) BaseContainer() *dagger.Container {
	return dag.Go(dag.Directory()).Base()
}

func (t GoSDK) DevContainer() *dagger.Container {
	return dag.Go(t.Source).
		Env().
		With(t.Dagger.devEngineSidecar()).
		WithWorkdir("sdk/go")
}

// Regenerate the Go SDK API
func (t GoSDK) Generate(ctx context.Context) (*dagger.Changeset, error) {
	return t.DevContainer().
		WithExec([]string{"go", "generate", "-v", "./..."}).
		WithExec([]string{"go", "mod", "tidy"}).
		Directory("../.."). // pop back to repo root
		Changes(t.Source()).
		Sync(ctx)
}

// Test the release
func (t GoSDK) ReleaseDryRun(ctx context.Context) (CheckStatus, error) {
	return CheckCompleted, t.Publish(
		ctx,
		"HEAD",
		true, // dryRun
		"https://github.com/dagger/dagger-go-sdk.git",
		"https://github.com/dagger/dagger.git",
		"dagger-ci",
		"hello@dagger.io",
		nil,
	)
}

// Publish the Go SDK
func (t GoSDK) Publish(
	ctx context.Context,
	tag string,

	// +optional
	dryRun bool,

	// +optional
	// +default="https://github.com/dagger/dagger-go-sdk.git"
	gitRepo string,
	// +optional
	// +default="https://github.com/dagger/dagger.git"
	gitRepoSource string,
	// +optional
	// +default="dagger-ci"
	gitUserName string,
	// +optional
	// +default="hello@dagger.io"
	gitUserEmail string,

	// +optional
	githubToken *dagger.Secret,
) error {
	version := strings.TrimPrefix(tag, "sdk/go/")

	if err := gitPublish(ctx, t.Dagger.Git, gitPublishOpts{
		sdk:          "go",
		source:       gitRepoSource,
		sourceTag:    tag,
		sourcePath:   "sdk/go/",
		sourceFilter: "if [ -f go.mod ]; then go mod edit -dropreplace github.com/dagger/dagger; fi",
		sourceEnv:    t.BaseContainer(), // Just need git and go installed
		dest:         gitRepo,
		destTag:      version,
		username:     gitUserName,
		email:        gitUserEmail,
		githubToken:  githubToken,
		dryRun:       dryRun,
	}); err != nil {
		return err
	}

	return nil
}

// Bump the Go SDK's Engine dependency
func (t GoSDK) Bump(_ context.Context, version string) (*dagger.Changeset, error) {
	// trim leading v from version
	version = strings.TrimPrefix(version, "v")

	versionFile := fmt.Sprintf(`// Code generated by dagger. DO NOT EDIT.

package engineconn

const CLIVersion = %q
`, version)

	layer := t.Dagger.Source.WithNewFile("sdk/go/engineconn/version.gen.go", versionFile)
	return layer.Changes(t.Dagger.Source), nil
}
